### PR TITLE
Add SharpLink

### PR DESCRIPTION
**Pull request by kotx**

### CODE REVIEW

**Comment by kotx** [comment]
Don't know whether to change `(Discord.Net)` to `(Discord.Net, C#)` because it doesn't support just C#, as far as I know.

**Comment by luaugg** [comment]
Would probably be better if you just put .NET as the “language” so as to be compatible with other langs that can use your lib.

Besides that, great job on the new lib!

**Comment by devoxin** [comment]
We didn't list this because the libs a WIP with a few bugs 🤔

**Comment by freyacodes** [comment]
I would put C# or .NET, at least for the sake of consistency.

**Comment by kotx** [comment]
(do not merge yet, need confirmation from @Devoxin)

**Comment by devoxin** [comment]
I believe SharpLink is now ready for production use so this could probably be merged (once conflicts are fixed)

**Review by freyacodes — APPROVED** [review]
:+1:

**Pull request merged**
