### PR TITLE
Add Lavalink.NET to Client Libraries

### PR DESCRIPTION
**Pull request by DevYukine**
Adds my own C# written Library for Lavalink to the Client Libraries, works with any C# Discord API Library.

### CODE REVIEW

**Comment by luaugg** [comment]
you could possibly change the targeted "language" from "C#" to just ".NET", similar to #112, especially since the name of your library ends with ".NET"

**Comment by DevYukine** [comment]
Alright done that 👍

**Review by freyacodes — APPROVED** [review]
Sorry for the delay. This LGTM.

**Comment by Frederikam** [comment]
Why did that review twice :thinking:

**Pull request merged**
