### PR TITLE
Working filter stuff

### PR DESCRIPTION
**Pull request by devoxin**

### CODE REVIEW

**Comment by freyacodes** [comment]
I've merged over a year's updates into the fork. I would like to hear if anyone has success with it.

Though I am told by @DaliborTrampota that vibrato doesn't work https://sourceb.in/jGUiAFO68S

**Comment by devoxin** [comment]
Yeah. I've never been able to get Vibrato to work. I asked Natan about this and he just said he copied some stuff off the internet and converted it to Java IIRC. Might have to write that filter off as a lost cause.

**Comment by freyacodes** [comment]
Oh well. We can just remove again

**Comment by DaliborTrampota** [comment]
> I've merged over a year's updates into the fork. I would like to hear if anyone has success with it.
> 
> Though I am told by @DaliborTrampota that vibrato doesn't work https://sourceb.in/jGUiAFO68S
>  

The vibrato can be fixed by updating lavadsp to version 0.7.something I dont know and cant check atm but even though the vibrato is fixed by updating the lavadsp the quality is bad there is some kind of noise/distortion that makes the vibrato almost unnoticeable

**Comment by DaliborTrampota** [comment]
> I've merged over a year's updates into the fork. I would like to hear if anyone has success with it.
> 
> Though I am told by @DaliborTrampota that vibrato doesn't work https://sourceb.in/jGUiAFO68S
>  

Also you should check https://github.com/Mandruyd/Lavalink/pull/1 this fork where I added new distortion effect from lavadsp and everything is working great only it has to be on jdk13

**Review by freyacodes — APPROVED** [review]
It's happening

**Comment by s4093120** [comment]
When is it going to be merged to the master

**Pull request merged**
