### PR TITLE
Auto voice reconnect toggle

### PR DESCRIPTION
**Pull request by Repulser**

### CODE REVIEW

**Comment by knight-ryu12** [comment]
also don't use wildcard import…
It'll bloat jar.

**Comment by freyacodes** [comment]
Please use a getter and setter instead of a constructor parameter.

>also don't use wildcard import…

Agreed

>It'll bloat jar.

Wait what

**Comment by schnapster** [comment]
>also don't use wildcard import…
>It'll bloat jar.

That's not how the import in Java works.
All it does is allow you to write the name of a class instead of the full qualifier.

**Comment by knight-ryu12** [comment]
Bloat Jar size, I should've choose word more wisely…

2017/12/08 午前7:29 "Frederik Ar. Mikkelsen" <notifications@github.com>:

Please use a getter and setter instead of a constructor parameter.

also don't use wildcard import…

Agreed

It'll bloat jar.

Wait what

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Frederikam/Lavalink/pull/37#issuecomment-350114374>,
or mute
the thread

**Comment by knight-ryu12** [comment]
really? wait… hm…

2017/12/08 午前7:30 "Dragon ryu" <knight.ryu12@gmail.com>:

**Comment by knight-ryu12** [comment]
what wth happened

**Review by freyacodes — APPROVED** [review]

**Pull request merged**
