### PR TITLE
[dev] Add prometheus metrics

### PR DESCRIPTION
**Pull request by schnapster**
Add basic metrics for logs and the JVM.

The metrics beans are fully conditional, so not opting in to metrics should have no impact™

No security has been added. Security is achieved by not exposing the host to public networks in the first place, or using a reverse proxy (and any security measures of the user's choice and the chosen reverse proxies' capability).

### CODE REVIEW

**Comment by freyacodes** [comment]
This doesn't look like a breaking change. Would it make sense to include it in v2?

**Comment by schnapster** [comment]
Yes. One moment.

**Comment by schnapster** [comment]
:ok_hand:

**Review by freyacodes — APPROVED** [review]
:ok_hand:

**Pull request merged**
