### PR TITLE
Update docs: added how-to setup IPv6

### PR DESCRIPTION
**Pull request by manybaht**
Added
Well-known server providers
- Hetzner
- Contabo

### CODE REVIEW

**Comment by duncte123** [comment]
What about OVH, Digital Ocean, Oracle Cloud, AWS, Azure, Google Cloud?

If you're gonna talk about providers you're better of taking generic linux

**Comment by topi314** [comment]
I think I would prefer this to be in a sub page?
```
- configuration
 - ipv6
   - Hetzner
   - Contabo
```

As duncte said a generic Linux would probably be nice too 

Thanks for working on this

**Comment by manybaht** [comment]
> I think I would prefer this to be in a sub page?
> 
> ```
> - configuration
>  - ipv6
>    - Hetzner
>    - Contabo
> ```
> 
> As duncte said a generic Linux would probably be nice too
> 
> Thanks for working on this

Done restructure the docs

**Comment by manybaht** [comment]
Added

- Check your IPv6
- Ubuntu/Debian
- DigitalOcean (Please just use TunnelBroker instead 💀)

**Comment by duncte123** [comment]
> Please just use TunnelBroker instead

Sounds like a good page to add as well ;)

**Comment by manybaht** [comment]
update a guide for Tunnelbroker while super sleepy might had some errors idk lol

**Review by topi314 — APPROVED** [review]

**Pull request merged**
