### PR TITLE
Socket null fix

### PR DESCRIPTION
**Pull request by Repulser**

### CODE REVIEW

**Comment by MrJacz** [comment]
Why not just make one pr for all changes you're going to make?

**Comment by freyacodes** [comment]
>Why not just make one pr for all changes you're going to make?

PRs should change one thing at a time to make them easy to merge and review.

**Comment by MrJacz** [comment]
I guess you guys have a different way of handling things then :)

**Comment by schnapster** [comment]
I was summoned by a proposed removal of a `@Nonnull` annotation without a replacement :eyes:

**Comment by Repulser** [comment]
@napstr Well the issue is it could return null if we choose not to select one if absent, whats the benefit in that annotation anyways?

**Review by freyacodes — APPROVED** [review]

**Comment by freyacodes** [comment]
@Repulser Some IDEs will warn you of potential NPEs when you don't already check

**Pull request merged**
