### PR TITLE
Experimental Magma version with Netty instead of Undertow

### PR DESCRIPTION
**Pull request by schnapster**

### CODE REVIEW

**Comment by freyacodes** [comment]
Is this still a draft?

**Comment by schnapster** [comment]
Noone has tested this so far (and reported back the results). Would you be able to run one of the FredBoat nodes on this build? Caution, I did not test this locally at all.

**Comment by freyacodes** [comment]
I might. Though it seems misleading to call this a draft. You're waiting for review and verification, you're not still working on it.

**Comment by schnapster** [comment]
The communication could have been indeed clearer, I only posted about this in #lavalink. In any case, this branch is not ready to be merged, until a proper magma version is released.

**Comment by schnapster** [comment]
Closing as there seems to be no interest in this.

**Pull request closed without merging**
