### PR TITLE
Add option to disable ytsearch and scsearch

### PR DESCRIPTION
**Pull request by duncte123**

### CODE REVIEW

**Comment by MrJacz** [comment]
if you're also gonna add an option to disable ytsearch why not add scsearch as well?

**Comment by duncte123** [comment]
> if you're also gonna add an option to disable ytsearch why not add scsearch as well?

Good idea, didn't think about that

**Review by schnapster — APPROVED** [review]

**Comment by schnapster** [comment]
LGTM.
@Frederikam ?

**Comment by freyacodes** [comment]
@napstr I'll aim to review it later this evening

**Review by freyacodes — APPROVED** [review]

**Comment by freyacodes** [comment]
Yep looks good

**Pull request merged**
