### PR TITLE
update lavaplayer & use official repo again

### PR DESCRIPTION
**Pull request by topi314**
official repo by sedmelluq is uptodate again so we should use this again :)

### CODE REVIEW

**Comment by freyacodes** [comment]
I don't have an overview of which is more up to date

**Comment by Skye-31** [comment]
> I don't have an overview of which is more up to date

@Frederikam 

https://discord.com/channels/125227483518861312/263484072389640193/770276771551379468

Edit: it should also actually be 1.3.52, not 1.3.51

**Comment by topi314** [comment]
> > I don't have an overview of which is more up to date
> 
> @Frederikam
> 
> https://discord.com/channels/125227483518861312/263484072389640193/770276771551379468
> 
> Edit: it should also actually be 1.3.52, not 1.3.51

oh mb then

**Comment by topi314** [comment]
Official Lavaplayer now has the Bandcamp fixes & additional twitch fixes

https://discord.com/channels/125227483518861312/263484072389640193/770423683223126046

**Review by freyacodes — APPROVED** [review]

**Pull request merged**
