### PR TITLE
Add wavelink back to README.md

### PR DESCRIPTION
**Pull request by EvieePy**
Adding WaveLink back to README as it is now un archived and beiing maintained.

### CODE REVIEW

**Comment by devoxin** [comment]
Something small - might I suggest grouping it with Pomice (and lavaplayer-py with lavasnek_rs) so the information column lines up? 😅

**Comment by EvieePy** [comment]
I think this is what you mean :)

**Comment by devoxin** [comment]
That looks perfect 🙂

**Review by freyacodes — COMMENTED** [review]
Are you sure you want to link the 1.0 branch? Maybe it is more helpful for your users if you change the default branch instead

**Comment by EvieePy** [comment]
I did that because we just had one more thing to implement before changing branches. But sure this can wait till that has been merged and I will update accordingly.

**Comment by freyacodes** [comment]
Just make sure you post a new PR

**Pull request merged**
