### PR TITLE
docu for no selectedTrack

### PR DESCRIPTION
**Pull request by topi314**
`audioPlaylist.getSelectedTrack()` may return `null` which then causes `Integer selectedTrack` to be `-1` as there is no `null` object in `audioPlaylist.getTracks()`

returning `-1` here causes the lavalink-client to throw a nice `Index -1 out of bounds` exception you can see here
https://hastebin.de/cidagilavo.yaml
https://github.com/Frederikam/Lavalink-Client/blob/a216e469638007463bbf641d1ababd7132129625/src/main/java/lavalink/client/io/LavalinkRestClient.java#L248

also there seem to be a problem with lavaplayer & yt playlists again:
https://github.com/sedmelluq/lavaplayer/issues/602

### CODE REVIEW

**Comment by freyacodes** [comment]
This is a breaking change. Would probably be better to fix Lavalink-Client and to document the `-1`

**Comment by topi314** [comment]
fair enough
I'll do that alter 👍🏻

**Comment by topi314** [comment]
it can't be null right 🤔

**Comment by topi314** [comment]
should I instead rebase this on master?

**Comment by freyacodes** [comment]
Sure

**Comment by topi314** [comment]
god lemme just open a new pr lmao

**Pull request closed without merging**
