### PR TITLE
Update Oshi

### LINKED ISSUE #858: Oshi dep - rare stats issue on Windows
## Description
I have a user that is using a 64-bit Windows 10 device to host Lavalink and his bot, and he encountered a stats issue/oshi issue when using a Lavalink.jar with oshi 5.7.4, this can be seen in his log at https://gist.githubusercontent.com/Cog-CreatorsBot/93ac8762eee30fed0b661f4f04fd7a3e/raw/3325e473fc269fae52350bd1d7b940fe6470e076/spring_1.log

```
2022-01-06 18:17:33.597  WARN 4508 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"
```

This issue is reported in https://github.com/oshi/oshi/issues/1710 and resolved with release 5.8.2.

## Version info
**Client used:** Red-Lavalink 0.9.0

Output of `java -version`:

Sorry I don't have the output of `java -version` as this issue was brought up to me in early 2022, was previously reported in https://github.com/freyacodes/Lavalink/pull/601 as I attempted to resolve it. The individual with this reported log was using Java 11.0.13.

### PR DESCRIPTION
**Pull request by topi314**
This pr updates [oshi](https://github.com/oshi/oshi) to `6.4.3` which should resolve https://github.com/lavalink-devs/Lavalink/issues/858

### CODE REVIEW

**Comment by topi314** [comment]
@aikaterna can you give this a test or see if this resolved the originally issue?

**Comment by ShitryaDima** [comment]
@topi314 I had the same error, it disappeared, but now there is a new one
`2023-06-09 14:09:05.606  WARN 10164 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Class Win32_PerfRawData_PerfProc_Process WHERE NOT Name LIKE "%_Total"`

**Comment by topi314** [comment]
can you provide more logs than that?

**Comment by ShitryaDima** [comment]
> can you provide more logs than that?

```D:\FatherBot\FatherBot v.2>"C:\Program Files\BellSoft\LibericaJDK-20\bin\java.exe" -jar Lavalink.jar
2023-06-09 14:15:48.265  INFO 29172 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 20.0.1 on DESKTOP-5Q68MLP with PID 29172 (D:\FatherBot\FatherBot v.2\Lavalink.jar started by Dmitriy in D:\FatherBot\FatherBot v.2)
2023-06-09 14:15:48.276  INFO 29172 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-06-09 14:15:49.252  INFO 29172 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.72 seconds (JVM running for 2.443)
2023-06-09 14:15:49.257  INFO 29172 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/lavalink-devs/Lavalink/issues/295
2023-06-09 14:15:49.342  INFO 29172 --- [           main] lavalink.server.Launcher                 :

←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        975a26c7eb1c0738caa487db0ed4f8dba4a34a48-SNAPSHOT
        Build time:     09.06.2023 08:59:52 UTC
        Branch          patch/update-oshi
        Commit:         975a26c
        Commit time:    09.06.2023 08:58:48 UTC
        JVM:            20.0.1
        Lavaplayer      1.4.1-original

2023-06-09 14:15:49.351  INFO 29172 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-06-09 14:15:50.413  WARN 29172 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-06-09 14:15:50.455  INFO 29172 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-06-09 14:15:50.473  INFO 29172 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1116 ms
2023-06-09 14:15:50.876  INFO 29172 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-06-09 14:15:51.704  INFO 29172 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2023-06-09 14:15:51.704  INFO 29172 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2023-06-09 14:15:51.710  INFO 29172 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2023-06-09 14:15:51.730  INFO 29172 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2023-06-09 14:15:51.771  WARN 29172 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2023-06-09 14:15:52.040  INFO 29172 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2023-06-09 14:15:52.053  INFO 29172 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2023-06-09 14:15:52.073  INFO 29172 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2023-06-09 14:15:52.240  INFO 29172 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-06-09 14:15:52.323  INFO 29172 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2023-06-09 14:15:52.331  INFO 29172 --- [           main] lavalink.server.Launcher                 : Started Launcher in 3.059 seconds (JVM running for 5.522)
2023-06-09 14:15:52.335  INFO 29172 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2023-06-09 14:16:11.689  INFO 29172 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-06-09 14:16:11.690  INFO 29172 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-06-09 14:16:11.691  INFO 29172 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-06-09 14:16:11.706  INFO 29172 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:35564
2023-06-09 14:16:11.925  INFO 29172 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established
2023-06-09 14:16:11.926  WARN 29172 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Library developers: Please specify a 'Client-Name' header. User agent: Python/3.8 aiohttp/3.8.1
2023-06-09 14:16:12.382  WARN 29172 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Failed to locate performance object for Processor Information in the registry. Performance counters may be corrupt. Pdh call failed with error code 0xC0000BB8
2023-06-09 14:16:12.382  WARN 29172 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Disabling further attempts to query Processor Information.
2023-06-09 14:16:12.895 ERROR 29172 --- [pool-2-thread-1] o.d.w.registry.HkeyPerformanceDataUtil   : Unable to parse English counter names in registry Perflib 009.
2023-06-09 14:16:12.900  WARN 29172 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Failed to locate performance object for Process in the registry. Performance counters may be corrupt. Pdh call failed with error code 0xC0000BB8
2023-06-09 14:16:12.900  WARN 29172 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Disabling further attempts to query Process.
2023-06-09 14:16:12.912  WARN 29172 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Class Win32_PerfRawData_PerfProc_Process WHERE NOT Name LIKE "%_Total"
2023-06-09 14:16:12.984 ERROR 29172 --- [pool-2-thread-1] lavalink.server.io.StatsCollector        : Exception while sending stats

java.lang.NullPointerException: Cannot invoke "oshi.software.os.OSProcess.getKernelTime()" because "p" is null
        at lavalink.server.io.StatsCollector.getProcessRecentCpuUsage(StatsCollector.kt:58) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.retrieveStats(StatsCollector.kt:106) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.createTask$lambda$0(StatsCollector.kt:69) ~[classes!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]```

**Comment by topi314** [comment]
do you happen to have the previous error aswell? (before updating to this pr)

**Comment by ShitryaDima** [comment]
do you mean before installing this patch? I had the same problem as @aikaterna. I also created an issue about it #874

**Comment by topi314** [comment]
that's what I was looking for ty

**Comment by topi314** [comment]
@ShitryaDima wanna give the latest build a try?, it should at least not throw anymore

**Comment by topi314** [comment]
@ShitryaDima 👀

**Comment by topi314** [comment]
we have been running oshi 6.4.3 for some time in v4, so this is prob safe to merge then

**Pull request merged**
