### PR TITLE
Replace oshi with calls to native JVM apis

### LINKED ISSUE #158: oshi.util.ParseUtil : Number is too big for a long parsing string to long array
Default config ~ discord.js-lavalink
```
2018-11-09 13:58:57.036 ERROR 18038 --- [pool-2-thread-1] oshi.util.ParseUtil : Number is too big for a long parsing string '18038 (java) S 1012 18038 1012 34817 18038 4202496 105074 996 4 1 1804 66 0 0 20 0 36 0 652454 5971169280 92864 18446744073709551615 4194304 4197664 140727357843456 140727357826128 140379713085335 0 0 0 16800975 18446744073709551615 0 0 17 3 0 0 0 0 0 0 0 0 0 0 18038 7164 7164 7164' to long array
```

### PR DESCRIPTION
**Pull request by schnapster**
Should solve the occasional bugs with oshi, as well as plain wrong and therefore useless CPU readings.

Probably only works on certain JVMs (OpenJDK, IBM/Eclipse J9), and probably not on Windows.

Fixes #158

### CODE REVIEW

**Comment by freyacodes** [comment]
I'm not willing to make Lavalink incompatible with most platforms. If we know which platforms this code supports, we could use oshi as a fallback. 

I assume this works on Zulu?

**Comment by schnapster** [comment]
Checked out all the JVMs available on sdkman, (:heavy_check_mark: == tests are green, meaning a non-error value is returned):
Linux:
11.0.3-zulu: :heavy_check_mark: 
11.0.3.hs-adpt: :heavy_check_mark: 
11.0.3-amzn: :heavy_check_mark: 
11.0.3-sapmchn: :heavy_check_mark: 
11.0.3-librca: :heavy_check_mark: 
11.0.3.j9-adpt: :heavy_check_mark:

**Comment by schnapster** [comment]
Actually OpenJ9 / IBM works too, it just needs a tad bit more time to populate the value. Adjusted the tests for that.

**Comment by MrJacz** [comment]
I've been using this build for about a week and a bit now.
Have had no errors from what I can see.

I used to have issues running in docker where it couldn't detect system time, that didnt happen using this.

**Comment by schnapster** [comment]
Not very relevant since noone should be hosting on it, but here's the test on a Mac:
11.0.3-zulu: ✔️
11.0.3.hs-adpt: ❌ 
11.0.3-amzn: ❌
11.0.3-sapmchn: ❌
11.0.3-librca: ✔️
11.0.3.j9-adpt: ✔️

Any windows volunteers around?

**Comment by aikaterna** [comment]
This branch fixed a variety of stats issues on a few installs I've seen: a Windows Server 2012 R2 device with an emulated processor, a Win10 amd64 device, and a i386 Win32 device. 

```
2019-06-18 18:13:03.788 ERROR 3796 --- [pool-4-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

java.util.ConcurrentModificationException: null
	at java.util.HashMap$Values.forEach(Unknown Source) ~[na:1.8.0_201]
	at lavalink.server.io.StatsTask.sendStats(StatsTask.java:67) ~[classes!/:na]
	at lavalink.server.io.StatsTask.run(StatsTask.java:53) ~[classes!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_201]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]
```
```
2019-06-16 12:53:02.943  WARN 5280 --- [pool-3-thread-1] oshi.util.platform.windows.PerfDataUtil  : Failed to add PDH Counter: \System\Context Switches/sec, Error code: 0xC0000BB8
2019-06-16 12:53:02.943  WARN 5280 --- [pool-4-thread-1] oshi.util.platform.windows.PerfDataUtil  : Failed to add PDH Counter: \System\Context Switches/sec, Error code: 0xC0000BB8
2019-06-16 12:53:02.945  WARN 5280 --- [pool-4-thread-1] o.h.p.windows.WindowsCentralProcessor    : Unable to enumerate performance counter instances for .
2019-06-16 12:53:02.945  WARN 5280 --- [pool-3-thread-1] o.h.p.windows.WindowsCentralProcessor    : Unable to enumerate performance counter instances for .
2019-06-16 12:53:02.949 ERROR 5280 --- [pool-4-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

java.lang.NullPointerException: null
	at oshi.util.platform.windows.PerfDataUtil.removeAllCounters(PerfDataUtil.java:227) ~[oshi-core-3.8.1.jar!/:3.8.1]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initPdhCounters(WindowsCentralProcessor.java:249) ~[oshi-core-3.8.1.jar!/:3.8.1]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:126) ~[oshi-core-3.8.1.jar!/:3.8.1]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:64) ~[oshi-core-3.8.1.jar!/:3.8.1]
	at lavalink.server.io.StatsTask.sendStats(StatsTask.java:91) ~[classes!/:na]
	at lavalink.server.io.StatsTask.run(StatsTask.java:53) ~[classes!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_211]
```
```
019-06-05 18:32:17.214 ERROR 27848 --- [pool-2-thread-1] oshi.util.ParseUtil: Number is too big for long parsing string '27848 (java) S 27846 27846 27846 34817 27846 4202496 41042 674 47 1 1221 84 0 1 20 0 23 0 700577324 04213504 32517 18446744073709551615 1091076096 109108388 3217311056 3217293792 3018444064 0 0 0 16800975 1844674407370955 615 00 17 1 0 0 10 0 0 0 0 0 0 0 27848 3807 3807 3807' to long array
```

**Comment by schnapster** [comment]
@aikaterna thank you for testing & taking the time to report it here! Do you happen to have the version & vendor handy of the JVM that you used on those platforms?

**Comment by aikaterna** [comment]
I am waiting to hear back from the individual with the Win10 machine.

i386 Win32 device:
java.version = 1.8.0_212
java.vendor = Oracle Corporation

x64 Win2012 R2 device:
java.version = 1.8.0_201
java.vendor = Oracle Corporation

**Comment by aikaterna** [comment]
The Win10 user got back to me.
java.version = 1.8.0_211
java.vendor = Oracle Corporation

If you have another distribution in particular that should be tried, I can get it installed on the Win2012 vps.

**Comment by schnapster** [comment]
Whatever makes sense to you, I have no idea about what works on Windows.

**Comment by aikaterna** [comment]
Getting a traceback on a Mac with this branch. This occurs immediately after a connection is started and intermittently throughout the connection as it attempts to send stats.

java.version = 11.0.1
java.vendor = Oracle Corporation
MacOS 10.12.5

```
2019-06-27 09:05:44.100 ERROR 1269 --- [pool-3-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

org.json.JSONException: JSON does not allow non-finite numbers.
	at org.json.JSONObject.testValidity(JSONObject.java:2214) ~[json-20180813.jar!/:na]
	at org.json.JSONObject.put(JSONObject.java:1813) ~[json-20180813.jar!/:na]
	at org.json.JSONObject.put(JSONObject.java:1720) ~[json-20180813.jar!/:na]
	at lavalink.server.io.StatsTask.sendStats(StatsTask.java:83) ~[classes!/:na]
	at lavalink.server.io.StatsTask.run(StatsTask.java:49) ~[classes!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by schnapster** [comment]
@Frederikam this PR seems to be stuck in limbo - is it not acceptable for the project, or does it require further work?

**Comment by freyacodes** [comment]
@napstr I'm still concerned about JVM compatibility. A fallback to OSHI would be ideal.

**Comment by schnapster** [comment]
A fallback triggered by what conditions?

**Comment by schnapster** [comment]
Also since we know that oshi itself sometimes provides bogus values, what would be the fallback to oshi?

**Comment by freyacodes** [comment]
One could run the collection once. If that throws an exception, Lavalink could permanently switch to use the old system.

If OSHI then fails then we're not left worse off than we are now.

**Comment by schnapster** [comment]
How about this:

Step 1: 
Attempt to collect via new CpuTimer class
If that returns an error value, return 0 as load.

Step 2:
If the JVM has been running for a few seconds (let's say 10s), and we continue getting errors values from using CpuTimer (at least 2 in a row), ask Oshi for the values.

Step 3:
If Oshi returns bogus values (see #210 for appropriate checks), keep returning 0 as load.


How does that sound?

**Comment by freyacodes** [comment]
Yeah that sounds great

**Comment by schnapster** [comment]
Cleaning up my PR Github tab, this has been open long enough and there appears to be no interest.

**Pull request closed without merging**
