### PR TITLE
Update springboot to 3.3.5

### PR DESCRIPTION
**Pull request by hwangsihu**

### CODE REVIEW

**Comment by topi314** [comment]
Any specific reason you want spring 3.3.5?

We usually bundle dependency updates as one big pr

**Comment by hwangsihu** [comment]
Because there may be bug fixes and stability improvements.
Ah, I tested it and it works fine.

**Comment by topi314** [comment]
There may?
In this case we will bump dependencies as we usually do

**Comment by hwangsihu** [comment]
I don't think it needs to be applied right now, so it would be better to merge it when the next version is released.

**Comment by hwangsihu** [comment]
https://github.com/hwangsihu/Lavalink/commit/9c321349b1e4d82dd52de6236dc0dfae428b4a61
What do you think about this? I haven't found any errors yet.

**Pull request closed without merging**
