### PR TITLE
Add LLTurbo client

### PR DESCRIPTION
**Pull request by Fyphen1223**
Add LLTurbo client.

### CODE REVIEW

**Comment by viztea** [comment]
This is literally a fork of Shoukaku with a name change...

**Comment by Fyphen1223** [comment]
Nah it supports voice receiving support on NodeLink...
Should I send this to NodeLink not here?

**Comment by Fyphen1223** [comment]
Um I think so, I will reopen this PR when I changed this client drastically. Sorry for disturbing.

**Comment by 1Lucas1apk** [comment]
I think this modification is not valid for adding a package that supports other software that is not lavalink, the right thing to do would be to go to NodeLink and ask them to add it there

**Comment by ThePedroo** [comment]
I totally disagree. NodeLink follows LavaLink protocols. If this is not accepted by that reason, clients that adds a plugin support shouldn't be added since it's not LavaLink.

I didn't look at the source, but if this is only the addition of NodeLink features, it should be a PR to shoukaku, not its own client. Now, if it's an almost entirely new base without being mostly the same, it's okay, as we have erela.js forks that are now clients.

**Comment by 1Lucas1apk** [comment]
I disagree, imagine a user making a fork in the coglink repo, and making a modification to a software that has different functionalities and then announcing it as a package with a different name, I feel like it's undervaluing the user's work, and it's not that question, he modified the shoudoku package to with nodelink functionalities, it's the same thing as having 2 shodouku only one with a different name, and functionality that won't work with lavalink, and it's unnecessary to try to put it on the client list, as you said in a certain part, if he at least hired the owner of the package to make it compatible it would also be ideal
Or ask another software to add it as a "nodelink" client

**Comment by ThePedroo** [comment]
Please do not put words in my mouth.

"but if this is only the addition of NodeLink features, it should be a PR to shoukaku"
"not its own client."
"almost entirely new base without being mostly the same, it's okay"

**Comment by devoxin** [comment]
As it currently stands this library isn't distinctive enough to warrant adding to the client library list, therefore it won't be added until it is at a point where it could be considered its own client, rather than just a fork of.

**Pull request closed without merging**
