### PR TITLE
Adding ongaku to the client.md list.

### PR DESCRIPTION
**Pull request by mplatypus**
Adding my client to the list of clients on the Lavalink website.

### CODE REVIEW

**Review by freyacodes — COMMENTED** [review]
Perhaps this library should be listed further up with the other purely Python libraries?

**Comment by mplatypus** [comment]
oh yeah sorry, didn't know how it was ordered 😅

**Review by mplatypus — COMMENTED** [review]
If I am doing this right, this should? have my fix, however, I am unsure.

Edit: I have no idea how to get my changed version of this into this pr sorry. I did move it down so it was alphabetical, however, I cannot figure out how to get it to show up here.

**Comment by freyacodes** [comment]
I am as confused as you are. It looks like you pushed to the correct branch in your fork, but it isn't reflecting here.

**Comment by topi314** [comment]
https://www.githubstatus.com/

>  Update - We're investigating issues with background jobs that are causing sporadic delays in pull request synchronization and reduced Actions throughput.

**Comment by mplatypus** [comment]
lmao, what a coincidence. I even googled to make sure I was doing the right thing, and it's a github issue xD

**Comment by topi314** [comment]
on that note: you should move it to the bottom of the python clients

**Comment by mplatypus** [comment]
I'll be able to do that tomorrow if I do remember. Otherwise, you are more than welcome to move it and merge the branch as you please.

**Comment by mplatypus** [comment]
okay, I have re-updated it to add mine at the bottom of the python list.

**Review by topi314 — APPROVED** [review]

**Pull request merged**
