### PR TITLE
More architectures JDA-NAS

### PR DESCRIPTION
**Pull request by Stonedestroyer**
Adds support for more architectures, will follow up with PR to udp-queue natives by @aikaterna .

### CODE REVIEW

**Comment by freyacodes** [comment]
These changes should be submitted together with the natives

**Comment by Stonedestroyer** [comment]
I assume a PR to this directory would be optimal https://github.com/sedmelluq/jda-nas/tree/master/udp-queue-natives/dist?

**Comment by freyacodes** [comment]
Not without a change in dependencies

**Comment by Stonedestroyer** [comment]
Understood, I will sort out the relevant parts. Will keep this PR in limbo.

**Comment by topi314** [comment]
closing this as it was implemented in https://github.com/freyacodes/Lavalink/pull/692

**Pull request closed without merging**
