### PR TITLE
Release v3.1

### PR DESCRIPTION
**Pull request by freyacodes**
* Replaced JDAA with Magma
* Added an event for when the Discord voice WebSocket is closed
* Replaced Tomcat and Java_Websocket with Undertow. WS and REST is now handled by the same server and port. Port is specified by `server.port`.

Further testing is appreciated.

### CODE REVIEW

**Comment by schnapster** [comment]
You can set magma to 0.6.1 here.

**Comment by freyacodes** [comment]
Ah true, you merged the PR

**Comment by shikhir-arora** [comment]
You could also set LP to @napstr's LP fix on Jitpack for the OPUS tags 👀

**Comment by schnapster** [comment]
I would prefer to avoid that, as my build has weird side effects of missing natives.

**Comment by shikhir-arora** [comment]
@napstr Ah okay, makes sense.

**Comment by GigaFyde** [comment]
In that case, could I interest you in this then? https://github.com/GigaFyde/lavaplayer-main

It's a highly stripped down version of lavaplayer which has been working like a charm for me for the past few days.
It has the Twitch fix, Artwork pr, and also the opus tag fix

And so far no side effects or errors

**Comment by freyacodes** [comment]
@GigaFyde FYI your repo violates the license https://github.com/sedmelluq/lavaplayer/blob/master/LICENSE

**Comment by GigaFyde** [comment]
My bad, completely forgot about the license, time to fix that

**Comment by GigaFyde** [comment]
Should be fixed now 😄

**Comment by freyacodes** [comment]
If we are going to switch to this alternative lavaplayer, I would do so in a separate release.

**Pull request merged**
