### PR TITLE
Bump lavaplayer to 1.3.7

### PR DESCRIPTION
**Pull request by schnapster**
image

### CODE REVIEW

**Comment by schnapster** [comment]
@SamOphis, you're on.

**Comment by devoxin** [comment]
I'll get you next time, Napstr 👀

**Review by freyacodes — APPROVED** [review]
:eyes:

**Comment by schnapster** [comment]
Nvm I just realized I'm not Fred :feelbadman:

**Comment by luaugg** [comment]
@napstr you're not fred but you still better watch out for the magma port to javascript 👀

**Pull request merged**
