### PR TITLE
Fixed typo in README.md

### PR DESCRIPTION
**Pull request by Fyphen1223**

### CODE REVIEW

**Comment by Fyphen1223** [comment]
This will be temp fix @topi314

**Comment by topi314** [comment]
neither does that link resolve to anything & I'm gonna wait for github to fix this
https://github.com/Fyphen1223/Lavalink/tree/lavalink-devs/CHANGELOG.md

**Comment by Fyphen1223** [comment]
I changed link and that should work, and this will be temp fix

**Comment by topi314** [comment]
it does not work, nor do I want a temp fix

**Comment by Fyphen1223** [comment]
k
sry to be annoying

**Comment by Fyphen1223** [comment]
but let me just say this
https://github.com/lavalink-devs/Lavalink/blob/master/CHANGELOG.md#400-beta1
this link is ok right?

**Comment by topi314** [comment]
that link would indeed work

**Comment by Fyphen1223** [comment]
and MD link is this

**Comment by topi314** [comment]
but linking to a static branch is just stupid, github should just fix it

**Comment by Fyphen1223** [comment]
why only this link is not working

like testbot is working properly
plugins.md is ok

**Comment by topi314** [comment]
I recommend asking github support

**Comment by Fyphen1223** [comment]
um that's true enough

**Pull request closed without merging**
