### PR TITLE
Update dependencies (experimental/magma)

### PR DESCRIPTION
**Pull request by shikhir-arora**
Mainly for magma 0.5.0 and jaap 1.3 accordingly but updated the rest. Shouldn't be any issues.

### CODE REVIEW

**Comment by schnapster** [comment]
Not sure if bumping logback is a good idea here. I think there were some breaking issues with this version unless slf4j is bumped too.

**Comment by schnapster** [comment]
See here: https://logback.qos.ch/news.html

> The 1.3.x series is Jigsaw/Java 9 modularized and requires slf4j-api version 1.8.x.

**Comment by shikhir-arora** [comment]
FWIW, we've been running this for ~2 days with no noticeable problems, using OpenJDK 11 (see screenshot). Since we're developing I have the LL log settings set to `trace` (root still set at `info` to avoid the mess 😆) which lets us see all the socket connections and events, and a quick look-through shows nothing breaking/not as it should be, and Sentry looks good as well.

carbon_2018-09-06_20-03-41

**Review by freyacodes — APPROVED** [review]

**Comment by schnapster** [comment]
Thanks (especially for the testing)!

**Pull request merged**
