### PR TITLE
Avoid http code 429 from youtube

### PR DESCRIPTION
**Pull request by freyacodes**
This is a PR because October

### CODE REVIEW

**Comment by schnapster** [comment]
LGTM

giphy (1)

**Comment by Dramex** [comment]
Hi, is there plans to support latest lavaplayer update which fix soundcloud with this branch?

**Comment by freyacodes** [comment]
No. This PR is still open because I forgot to close it after merging #235.

You should find everything you need on the dev branch.

**Comment by freyacodes** [comment]
Nevermind. It was merged into this branch. Updating lavaplayer...

**Pull request merged**
