### PR TITLE
feat: Single APM across all WS connections as default

### PR DESCRIPTION
**Pull request by Xavinlol**

### CODE REVIEW

**Comment by schnapster** [comment]
What is the benefit of a singleton APM? Why is that not the default? Just curious. I also think it might be worth documenting that info.

**Comment by DevYukine** [comment]
ImageOne
ImageTwo
ImageThree

We discussed this one on discord already, since a lot of people dont use Java to connect to LL and have multiple ws connections due to scaling of other languages, LL creates one APM for each WS which can lead into a ton of Threads from LP Threadpools & Spamming GC warnings since each APM does GC Warning on its own which also isn't great

**Comment by Xavinlol** [comment]
Basically what @DevYukine said. And i didn't set it to default so it's nothing breaking (created an APM for each WS connection before)

**Comment by schnapster** [comment]
Are there any drawbacks? I would just make it the default (and only) tbh.

**Review by freyacodes — APPROVED** [review]

**Pull request merged**
