### PR TITLE
Add java json API

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by duncte123** [comment]
It would be a good idea to add serialisation/deserialisation helpers as well

**Comment by DRSchlaubi** [comment]
> It would be a good idea to add serialisation/deserialisation helpers as well

https://github.com/lavalink-devs/Lavalink/blob/67ff059c92464716b24bd2ff6993a054ca519e85/protocol/src/commonMain/kotlin/dev/arbjerg/lavalink/protocol/v4/utils/serialization.kt

**Review by duncte123 — APPROVED** [review]
Meant objects instead of just strings, but this will do for now

**Comment by DRSchlaubi** [comment]
It allows for serialization of JsonPrimitive, JsonArray and JsonObject

**Comment by duncte123** [comment]
> It allows for serialization of JsonPrimitive, JsonArray and JsonObject

But what about 
```java
public record MyTrackUserData(long userId, String anotherArg) {}
```

Currently it cannot handle this for java users

**Comment by DRSchlaubi** [comment]
> > It allows for serialization of JsonPrimitive, JsonArray and JsonObject
> 
> But what about
> 
> ```java
> public record MyTrackUserData(long userId, String anotherArg) {}
> ```
> 
> Currently it cannot handle this for java users

Well yeah, but kotlinx.serialization has a compiler plugin, which generates the serializer (this is what @Serializable does), you cannot do that for a java record, so I can't handle that

**Comment by topi314** [comment]
replaced by https://github.com/lavalink-devs/lavalink-client/pull/12

**Pull request closed without merging**
