### PR TITLE
Bump lavaplayer

### PR DESCRIPTION
**Pull request by Walkyst**
[Change log](https://github.com/Walkyst/lavaplayer-fork/releases/tag/1.3.98)

### CODE REVIEW

**Comment by devoxin** [comment]
> Email and password fields are blank, age restricted videos will throw exceptions

Does 1.3.98 make a TV request if these fields are omitted?

**Comment by Walkyst** [comment]
You mean TV auth request or age restriction bypass with TVHTML5?

**Comment by devoxin** [comment]
The TVHTML5 workaround

**Comment by Walkyst** [comment]
Then yes, it will try

**Comment by devoxin** [comment]
Perhaps it's worth updating the message to reflect that email + password aren't strictly required?

**Review by devoxin — APPROVED** [review]

**Review by topi314 — APPROVED** [review]

**Comment by flav-code** [comment]
we can still use the old method ?

**Comment by topi314** [comment]
Yt cookies got removed so no

**Pull request merged**
